# Generated by Django 2.2.7 on 2019-12-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180620_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_animal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
